### PR TITLE
Update script and IP list

### PR DESCRIPTION
**Pull request by Attolis**
- Maxmind has been updated and now requires login in order to download the files required to run `./bin/update.js`. This PR fixes the script to run using files located in the local directory where it is being run.

### CODE REVIEW

**Comment by ms76** [comment]
@Attolis I have added the target version of node.js to run the tests (#20).
It will run when you merge the latest master and push again.

**Comment by Attolis** [comment]
@ms76 Thanks! Just updated this branch and the tests were successful.

**Comment by nezumi650** [comment]
@Attolis LGTM!

**Comment by Attolis** [comment]
@nezumi650 Thank you! 😄

**Pull request merged**
